### 高级会计师评审系统
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=008ebeba-88b3-4957-b245-12b4f797a088 HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 福建省非税收入和财政票据综合管理系统
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=0ca67772-b460-45ca-b7ad-0d3710c01eef HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 扶贫
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=bb2f6a27-5669-4939-84c0-d34dc68e090e HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 预算绩效
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=354cf2bb-eade-4b05-8446-5b376df6cd3d HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 部门预算
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=7454a13f-0ea8-421b-840e-5ee11fd6dc52 HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 工资管理系统
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=febec97f-bfcd-4558-8345-30f2a4fb139e HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 注册会计师业务报备系统
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=f7a690b1-22b0-4a7d-9558-e3bdf82f6bcd HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 国库集中支付
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=221f8cfc-b661-4363-9d78-d5af3e2514da HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 公务卡
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=cc86c992-383a-4a41-9951-3f05afa485f1 HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 财政编报
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=f51ed3ca-0a72-4c84-a418-b1c21c0feef3 HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 资产评估协会信息
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=e3cfb00d-7953-42a0-84cc-7e5808bba0a8 HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 资产管理信息
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=eb2c1527-bbbd-4b34-b710-98057a47c755 HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 非税收入收缴系统
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=e7aec60c-2ab9-4622-a671-f4132eeb761b HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive

### 总预算会计账务系统
GET /depserver/api/v1/interfaceExchange/listExchangeByPkCatalog?0.6732150536147945=&pk_catalog=f75bea47-8942-41f0-a4d8-4667a7039c1b HTTP/1.1
Host: 10.100.11.52:7001
Cookie: JSESSIONID=2861812b-7364-4afb-9ea4-559aaa9a3c22
User-Agent: Apifox/1.0.0 (https://www.apifox.cn)
Accept: */*
Cache-Control: no-cache
Host: 10.100.11.52:7001
Connection: keep-alive
